# Generated by Django 4.0 on 2021-12-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0003_remove_watchlist_movies_movie_movies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movies',
            new_name='watchlist',
        ),
    ]
